Thanks contribubtor and feedback form link
pycon-mentored-sprints/write-ups pull request #9
Opened 2019-05-07 14:37 UTC by Mariatta

2019-05-08 11:23 UTC, Nikoleta-v3 commented on email_campaigns/thanks-contributor-email.md
> +We are including an anonymous survey to hear your thoughts on what we can do even better next time.
Same comments as the other `PR`

2019-05-08 11:23 UTC, Nikoleta-v3 commented on email_campaigns/thanks-contributor-email.md
> +We're thankful to our mentors for volunteering their time and sharing their knowledge
Can we include a link where all the mentors are listed?

2019-05-09 18:17 UTC, nnja requested changes
minor nit and question

2019-05-09 18:17 UTC, nnja commented on email_campaigns/thanks-contributor-email.md
> +# Thanks to y'all
Same comment here https://github.com/pycon-mentored-sprints/write_ups/pull/8#discussion_r282603848

2019-05-09 18:17 UTC, nnja commented on email_campaigns/thanks-contributor-email.md
> +From Tania, Nina, Nikoleta & Mariatta
Should we include a way to keep this community active before the next event?

Mailing list? Newsletter for news and updates? Slack channel somewhere (not a new slack)?

2019-05-22 03:05 UTC, nnja commented on email_campaigns/thanks-contributor-email.md
> +We're aware of several issues occurred during the mentored sprint, such as late
```suggestion
We're aware of several issues that occurred during the mentored sprint, such as a late
```

2019-05-22 04:43 UTC, nnja commented
👍 from me pending newsletter details from @trallard

2019-05-23 10:41 UTC, trallard reviewed
All looks good to me

2019-05-23 10:41 UTC, trallard commented on email_campaigns/thanks-contributor-email.md
> +To get updated about future mentored sprint for diverse beginners events, you
To get updates about future mentored sprint for diverse beginners events, you

2019-06-19 16:40 UTC, Mariatta commented
Email was sent June 1, 2019

2019-06-19 16:40 UTC, merged